export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_USER = 'SET_USER';
export const SET_ADMIN_ARTICLES = 'SET_ADMIN_ARTICLES';
export const SET_CURRENT_ARTICLE = 'SET_CURRENT_ARTICLE';
export const SET_ADMIN_ARTICLES_TOTAL = 'SET_ADMIN_ARTICLES_TOTAL';
export const SET_ARTICLES_TOTAL = 'SET_ARTICLES_TOTAL';
